/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;

/**
 *
 * @author user
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonJugador = new javax.swing.JButton();
        jLabelTurno = new javax.swing.JLabel();
        jButtonTirar = new javax.swing.JButton();
        jLabelPuntuacion = new javax.swing.JLabel();
        txtjugador = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        JLabelJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido al juego de Craps");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese la cantidad de jugadores: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jButtonJugador.setText("Confirmar");
        jButtonJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 183, -1, 30));

        jLabelTurno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTurno.setText("Turno del Jugador:");
        getContentPane().add(jLabelTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 40));

        jButtonTirar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonTirar.setText("Tirar");
        jButtonTirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTirarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 90, 30));

        jLabelPuntuacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPuntuacion.setText("Tu puntuación fue de:");
        getContentPane().add(jLabelPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, -1, -1));

        txtjugador.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(txtjugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 110, 20));

        txtnumero.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 60, 20));

        JLabelJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tablero.png"))); // NOI18N
        getContentPane().add(JLabelJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugadorActionPerformed
        // TODO add your handling code here:
        txtnumero.setText(txtjugador.getText());
    }//GEN-LAST:event_jButtonJugadorActionPerformed

    private void jButtonTirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTirarActionPerformed

        
                
    }//GEN-LAST:event_jButtonTirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelJugador;
    private javax.swing.JButton jButtonJugador;
    private javax.swing.JButton jButtonTirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPuntuacion;
    private javax.swing.JLabel jLabelTurno;
    private javax.swing.JTextField txtjugador;
    private javax.swing.JTextField txtnumero;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelattiveTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
      
}
